language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install poetry
  - poetry build
  - pip install dist/*tar.gz
# command to run tests
script: pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)