language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install poetry
  - poetry install
# command to run tests
jobs:
  include:
    - stage: Tests
      script: poetry run pytest
    - stage: Flake8
      script: poetry run flake8
after_success:
  - bash <(curl -s https://codecov.io/bash)